### ISSUE TITLE
Unrelated Issue

### ISSUE THREAD

**Issue by kris-singh** [pytorch/extension-cpp#25]
Learning the internals of pytorch. I need to test some c++ functions that I build with aten. 
I have followed this example https://github.com/goldsborough/examples/blob/cpp/cpp/mnist/CMakeLists.txt.
I don't want to write the CMakeList file for every source file that i write. Is there a way to link against the .dylib files using -l flag. I tried g++ --std=c++11 -l/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/torch/lib/libtorch.dylib -I/anaconda3/envs/pytorch1.0/lib/python3.6/sitepackages/torch/lib/include  example-app.cpp -o example but this fails. 

Could you let me know a way to do this? Or why is it preferred to make CmakeFiles for small examples

cc: @goldsborough

**Comment by goldsborough** [comment]
I recommend using the `CMakeLists.txt` because it will automatically do the right thing when PyTorch libraries get updated. If you want to see the full command that CMake ends up running, you can use `make VERBOSE=1` when compiling, then you'll see the full compiler invocation including the linker flags and such, and you can copy paste those into your terminal if you want to.

**Comment by kris-singh** [comment]
Thanks @goldsborough this was very helpful. As I already mentioned I am learning the internals of pytorch for better understanding and also it will be helpful in my future research projects. I get really stuck on some portions is there a way to reach you (if possible) to ask these questions. Since I don't feel raising an issue everytime is such a good idea, I know about pytorch forums but I think questions get lost there due to the volume of the questions.

**Comment by goldsborough** [comment]
You can reach us on the PyTorch slack. See https://pytorch.org/resources
